---
# UPDATE TIME OF TASK: 20 = 1 SEG
interval-time: 20

# ALLOW WORLDS ON RUN TITLES
worlds:
  world:
    title:
    - '&fserver title'
    - '&aserver title'
    lines:
    - '&7Player: &3{RAINBOW}{PLAYER}'
    - '&7Online: &3{ONLINE_PLAYERS}'
    - '&7World Name: &3{WORLD_NAME}'
    - '&7World Player: &3{WORLD_PLAYERS}'
    - '&7Player X: &a{PLAYER_X}'
    - '&7Player Y: &a{PLAYER_Y}'
    - '&7Player Z: &a{PLAYER_Z}'
  world2:
    title:
    - '&fserver title'
    - '&aserver title'
    lines:
    - '&7Player: &3{RAINBOW}{PLAYER}'
    - '&7Online: &3{ONLINE_PLAYERS}'
    - '&7World Name: &3{WORLD_NAME}'
    - '&7Money: &a{MONEY}'
    - '&7RANK: &a{RANK}'

# DEFAULT TITLE IF EMPTY WORLDS
default:
  title:
  - '&bserver title'
  - '&aserver title'
  lines:
  - '&7Player: &3{PLAYER}'
  - '&7Online: &3{ONLINE_PLAYERS}'
  - '&7World Name: &3{WORLD_NAME}'
  - '&7World Player: &3{WORLD_PLAYERS}'
...